### ISSUE TITLE
xWaitForCluster not accepting "Credential" parameter

### ISSUE THREAD

**Issue by aarsan** [PowerShell/xFailOverCluster#1]
Receiving the following error when trying to run xWaitForCluster on node attempting to join the cluster:

Chef::Exceptions::PowershellCmdletException
-------------------------------------------
Powershell Cmdlet failed: Invoke-DscResource : Undefined property Credential

It seems that maybe that parameter was removed but the documentation hasn't been updated?

**Comment by aarsan** [comment]
It appears as though the "xWaitForCluster" part is not ready yet, from what I can tell. I was assuming it would allow a node to join the cluster once it was ready but I don't see the code that does that yet. Or, am I missing something?

**Comment by DdenBraver** [comment]
@aarsan I noticed you posted this some time ago, However I would still like to try to answer your question.

I think xWaitForCluster was only created to check if the cluster is available for an additional node to join it.
Where you first use xWaitforCluster to see if the cluster exists, followed by xCluster to join the cluster.

I personally use it in the following order:
WaitforAll, xWaitforCluster, xCluster

**Comment by TravisEz13** [comment]
@aarsan  I tend to agree with @DdenBraver .
