### ISSUE TITLE
xCluster: Support DHCP addresses for clusters

### ISSUE THREAD

**Issue by wasabii** [PowerShell/xFailOverCluster#109]
Should support more than just a static IP.

**Comment by johlju** [comment]
I agree! I label this as "Help wanted" until someone starts work on this one.

**Comment by wasabii** [comment]
Going over the code... I don't see why it's even a parameter? If you don't specify StaticAddress, doesn't Create Cluster work anyways?

**Comment by johlju** [comment]
Yes, New-Cluster will work without specifing StaticIpAddress. It would use the default network with DHCP then I guess. But the parameter StaticIpAddress is needed to specify one or more up addresses to be used, but it should not be mandatory. And it should also be an array so it possible to add more than one network.

See here:
https://technet.microsoft.com/en-us/library/ee460973.aspx

**Comment by wasabii** [comment]
Right, so, immediately, a decent change would be to just make it not mandatory.

**Comment by johlju** [comment]
I agree. And also make sure New-Cluster is called properly, without the StaticIpAddress when it's not assigned a value.
