### ISSUE TITLE
xCluster: Ability to ignore 1 or more networks on cluster creation.

### ISSUE THREAD

**Issue by TraGicCode** [PowerShell/xFailOverCluster#143]
It would be nice to have this feature implemented.  Most specifically i found out i need this when spinning up a machine in virtualbox with vagrant so i can ignore the Adapter 1: which is the Nat Adapter

https://technet.microsoft.com/en-us/library/ee460973.aspx

**Comment by johlju** [comment]
Yes, that would be a great addition to this resource. I labeled it as help wanted, so that anyone can feel free to add this to the resource.

**Comment by TraGicCode** [comment]
Hey @johlju ,

In order to start working on this feature what is the process of running the unit tests?  I don't see any documentation on this.

**Comment by johlju** [comment]
Hmm. Maybe it's not to well documented. You can read about it here in the [TestGuidlines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md). 

To run all tests

```
Invoke-Pester 
```

To run just one test

```
Invoke-Pester <path-to-test>
```

To run test with code coverage

```
Invoke-Pester <path-to-test-file> -CodeCoverage <path-to-module-file>
```

**Comment by TraGicCode** [comment]
Got it.  I actually tried that but it turns out my pester was on 3.x and not 4.x and that is not compatible with these tests.  Thanks 🗡

**Comment by johlju** [comment]
If you start working on this, let me know and I label this one as in progress. Also when you work on this, if you have any questions let me know, I'm happy to help :)

**Comment by johlju** [comment]
Ah yes. Pester 4 handles nested describe and context blocks. Version 3 did not.

**Comment by TraGicCode** [comment]
Sure thing i'm about to start!  Getting the tests running first then i will try and TDD through this.  I'm from a puppet rspec background so i'll see what i can do.  Luckily pester copied rspec so the tests look identical

**Comment by johlju** [comment]
Nice! I like TDD too! I will label this one as in progress :smile:

**Comment by TraGicCode** [comment]
These don't actually modify my system do they?  Its taking an awefully long time

![image](https://user-images.githubusercontent.com/6224270/30230757-441c308a-94ad-11e7-8b07-b6a32c28eb5c.png)

**Comment by johlju** [comment]
They do not. But those are the unit tests for the test framework (repo DscResources.Tests). You can skip those by change folder to the Tests folder, or Tests/Unit folder and run Invoke-Pester from there. By default Pester do recursive search for all *.Tests.ps1 in all folder from current folder.

**Comment by johlju** [comment]
I usually run in Unit/Tests folder when I write tests and usually only run the test file I currently work on until the end, when I run all tests (in the unit folder) just to verify I did not change anything I shouldn't have.

**Comment by TraGicCode** [comment]
Okay let me do that.  It's still stuck

**Comment by TraGicCode** [comment]
Awesome worked.  all tests passed!

![image](https://user-images.githubusercontent.com/6224270/30230998-80020d94-94ae-11e7-8172-5a6602e592bf.png)

**Comment by johlju** [comment]
Great! :smile:
