### ISSUE TITLE
Can't Add Second Node to the existing Cluster Using xfailovercluster module

### ISSUE THREAD

**Issue by dead8171** [PowerShell/xFailOverCluster#157]
I am trying to add the second node to the cluster that is being created by the primary node, both the nodes are domian joined and are in an availability set, all of my infrastructure is in azure and I am using azure automation account to pull the details from the server, Is anyone facing this issue please let me know about this.
I am running the script to join node onto the secondary node and the script contains the IP of the Primary Node as well.

**Comment by johlju** [comment]
@dead8171 Is this the same issue as being discussed in issue #148? 

Does the availability set have different network subnet? if so, then you might encounter issue #154.

**Comment by dead8171** [comment]
@johlju No I have all the machines in the same A.V set and they are in same Subnet under the V.net.

**Comment by dead8171** [comment]
@johlju Am I going to get any fix for this issue cauz I have been struggling with this from September and its been december and no fix for this

**Comment by johlju** [comment]
Closing this issue as it is a duplicate of issue https://github.com/PowerShell/xFailOverCluster/issues/148, let's track it in issue #148.
