### ISSUE TITLE
xClusterProperty: New resource proposal

### ISSUE THREAD

**Issue by markgossa** [PowerShell/xFailOverCluster#169]
Hi,

I've just had to set the cluster thresholds on one of our customer clusters and thought it would be good if the DSC resource had (SameSubnetDelay, SameSubnetThreshold etc). I'm just creating a new DSC Resource for my use. Is it worth me making a pull request and getting this new DSC resource added to xFailOverCluster?

Mark

**Comment by johlju** [comment]
We are always happy for all contributions! I'm not seeing any current PR is working on this, so please send in a PR! Do you see this as a change to a existing PR, or do you see this as being a new resource? If a new resource, then could you also please submit the schema.mof here so others can discuss this new resource?

**Comment by markgossa** [comment]
Hi @johlju I think it's best to create a new DSC resource for this. Example schema.mof is attached.
[xClusterThresholds.schema.mof.txt](https://github.com/PowerShell/xFailOverCluster/files/1616365/xClusterThresholds.schema.mof.txt)



It may be that it's better to make a DSC resource which is called xClusterProperty and use this to set other properties of the cluster in addition to the thresholds e.g. ClusSvcHangTimeout, ClusterLogLevel, ClusterLogSize, PreferredSite, QuarantineDuration, QuarantineThreshold etc. Let me know what you (and everyone else) thinks.

**Comment by johlju** [comment]
Sounds good to me. So this is the schema you got so far. Updated it with the correct resource name. 

>Please note the prefix 'MSFT_' in the class name, it's mandatory. Both in the class name as well as the resource folder and resource files should start with this prefix (see another resource for reference).

```
[ClassVersion("1.0.0.0"), FriendlyName("xClusterProperty")]
class MSFT_xClusterProperty : OMI_BaseResource
{
    [Key, Description("Cluster name")] string Name;
    [Write, Description("Cluster SameSubnetDelay property")] string SameSubnetDelay;
    [Write, Description("Cluster SameSubnetThreshold property")] string SameSubnetThreshold;
    [Write, Description("Cluster CrossSubnetDelay property")] string CrossSubnetDelay;
    [Write, Description("Cluster CrossSubnetThreshold property")] string CrossSubnetThreshold;
};
```

Labeling this as a new resource, and as in progress (sounds like you want to send in a PR for this). Let me know if you need any help with the process at any time! Looking forward to the PR! 😄

**Comment by markgossa** [comment]
Great. Thanks! I'll get a PR over to you in the next few days.

**Comment by markgossa** [comment]
@johlju - PR just sent over for review. Let me know what changes you need :smile:

**Comment by johlju** [comment]
Awesome! I will review it tonight (my timezone). Thank you for contributing that! :smile:
