### ISSUE TITLE
Master Branch update

### ISSUE THREAD

**Issue by Blankf** [PowerShell/xFailOverCluster#172]
Hi Guys, 

is it possible to make a new release, 1.9.0.0 or so.
we are missing great bugfixes and additions.

Thanks.

**Comment by johlju** [comment]
Next release will be on February 7th if everything goes as planned. Master branch will be updated with the dev version, and master branch will be release to PowerShell Gallery. Closing this issue at this time.

**Comment by Blankf** [comment]
Thank you very much!

2018-01-31 22:13 GMT+01:00 Johan Ljunggren <notifications@github.com>:
