### ISSUE TITLE
Access Denied Error

### ISSUE THREAD

**Issue by devanshujoshi** [PowerShell/xFailOverCluster#185]
Hi Team,
I am facing an issue with xFailoverCluster Resource . MSFT_xCluster resource is not able to add the node to the cluster. I have pre-staged the cluster name object(CNO) in the AD OU , that is also disabled. 

I am getting below error: 
{
    "Exception":  {
                      "Message":  "PowerShell DSC resource MSFT_xCluster  failed to execute Set-TargetResource functionality with error message: The running command stopped because the preference variable \"ErrorActionPreference\" or common parameter is set to Stop: There was an error adding node \u0027VMNAME\u0027 to the cluster\n    You do not have administrative privileges on the server \u0027VMNAME\u0027.\n    Requested registry access is not allowed. ",
                      "Data":  {

                               },
                      "InnerException":  {
                                             "ErrorRecord":  "There was an error adding node \u0027VMNAME\u0027 to the cluster\n    You do not have administrative privileges on the server \u00277VMNAME\u0027.\n    Requested registry access is not allowed.",
                                             "WasThrownFromThrowStatement":  false,
                                             "Message":  "The running command stopped because the preference variable \"ErrorActionPreference\" or common parameter is set to Stop: There was an error adding node \u0027XXXXXXXXX(VMNAME)\u0027 to the cluster\n    You do not have administrative privileges on the server \u0027VMXXXXXXX\u0027.\n    Requested registry access is not allowed.",
                                             "Data":  "System.Collections.ListDictionaryInternal",
                                             "InnerException":  null,
                                             "TargetSite":  "System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] Invoke(System.Collections.IEnumerable)",
                                             "StackTrace":  "   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)\r\n   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)\r\n   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)\r\n   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)\r\n   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)\r\n   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32\u0026 resultStatusHandle, Collection`1\u0026 result, ErrorRecord\u0026 errorRecord, PSModuleInfo localRunSpaceModuleInfo)",
                                             "HelpLink":  null,
                                             "Source":  "System.Management.Automation",
                                             "HResult":  -2146233087
                                         },
                      "TargetSite":  null,
                      "StackTrace":  null,
                      "HelpLink":  null,
                      "Source":  null,
                      "HResult":  -2146233079
                  },
    "TargetObject":  null,
    "CategoryInfo":  {
                         "Category":  7,
                         "Activity":  "",
                         "Reason":  "InvalidOperationException",
                         "TargetName":  "",
                         "TargetType":  ""
                     },
    "FullyQualifiedErrorId":  "ProviderOperationExecutionFailure",
    "ErrorDetails":  null,
    "InvocationInfo":  null,
    "ScriptStackTrace":  null,
    "PipelineIterationInfo":  [

                              ]
}

Any pointers on how to fix it. Thanks !!

**Comment by johlju** [comment]
Are you adding the first node to the cluster?
Could you please provide the configuration you are using, obfuscate any sensitive information? 
Are you running this on an Azure VM?
