### ISSUE TITLE
xCluster : No RSAT-Clustering-Mgmt feature in the example 

### ISSUE THREAD

**Issue by mdaniou** [PowerShell/xFailOverCluster#193]
Hi,

Is it intended not to have the feature RSAT-Clustering-Mgmt in the examples ?
If not I could probably update them.

Thanks

**Comment by johlju** [comment]
The examples are meant to to only install the minimum required components. Is the RSAT-Clustering-Mgmt only needed for the graphical user interface? Then that is optional since it is not needed for Server Core?

**Comment by mdaniou** [comment]
It is indeed for graphical only. So I understand this is intentional. However, I am not sure of the number of admin that decide to use Server Core.

**Comment by johlju** [comment]
Those that don't and need to manage the server locally could add this manually. Those that administer the servers remotely (regardless of Core or Desktop Experience) don't need this. I think examples should only show the minimal configuration needed to get things working.
But sure, we could add a new example on how to add the graphical components. But if so, I think it should be added as a separate example.

**Comment by mdaniou** [comment]
Ok I understand, thanks ! :)
