### ISSUE TITLE
xCluster - Paused node should not return a false test

### ISSUE THREAD

**Issue by OxHobbs** [PowerShell/xFailOverCluster#201]
#### Details of the scenario you tried and the problem that is occurring
The xCluster resource attempts to add a node to a cluster if it is in a **paused** state.  There are many valid reasons a cluster node might be in a cluster and be paused; such as, rolling updates or maintenance happening within the cluster.  Therefore, a paused node should not fail a ```Test-TargetResource```

#### Verbose logs showing the problem
Node attempts to add itself to a cluster even if it is already a member and is 'paused'

#### Suggested solution to the issue
Do not return false on the test method call if the node is in the cluster and is in a 'paused' state.

#### The operating system the target node is running
Windows Server 2016

#### Version and build of PowerShell the target node is running
5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
1.12.0.0

**Comment by johlju** [comment]
Thanks you so much for fixing this @OxHobbs!
