### ISSUE TITLE
FileShare Witness 

### ISSUE THREAD

**Issue by aultt** [PowerShell/xFailOverCluster#21]
Would be beneficial to have a resource to configure quorum.  Specifically FileShare Witness is often used in SQL Server clusters.

**Comment by johlju** [comment]
There is a pull request for this already sent in. But it has been stalled in the review process. I have used that pull request branch to set up file share witness.

**Comment by johlju** [comment]
See pull request #11

**Comment by aultt** [comment]
Looks like it is not actively being worked need to see if we can resurrect it.

Troy Ault | Premier Field Engineering
Office: (917) 388-1040  | Email: troyault@microsoft.com<mailto:troyault@microsoft.com>

Premier Support: 1.800.936.3100 | Premier Online https://premier.microsoft.com<https://premier.microsoft.com/>
[MSFT_logo]

**Comment by johlju** [comment]
Haven't looked at the PR for a while. Might be that @claudiospizzi is waiting for the review or worse if the review is waiting for code change.

**Comment by aultt** [comment]
@claudiospizzi  Are you still actively working this?  Would like to see this get merged please let me know if I can be of assistance.
