### ISSUE TITLE
xCluster`s Get function will fail

### ISSUE THREAD

**Issue by sosato** [PowerShell/xFailOverCluster#28]
xCluster module`s get function will fail, due to using Get-ClusterGroup Cmdlet.
> $address = Get-ClusterGroup -Cluster $Name -Name "Cluster IP Address" | Get-ClusterParameter "Address"

"Cluster IP Address" is not Cluster Group, it is Cluster Resource. We should use Get-ClusterResource Cmdlet.

**Comment by johlju** [comment]
You are correct. I verified this. I think the Get-ClusterResource has 'fallen out' of the code :/
I think it meant to be like this.

```
Get-ClusterGroup -Cluster 'MyCluster' |
    Get-ClusterResource -Name 'Cluster IP Address' |
        Get-ClusterParameter 'Address'
```

That will return the IP-address.

**Comment by johlju** [comment]
This bug was introduced in PR #22. `Get-ClusterResource` was remove (by mistake), and it was apparently not caught by review or by tests.
https://github.com/PowerShell/xFailOverCluster/pull/22/files#diff-8b089640da31e97f466dca5697c68d6dL39

**Comment by johlju** [comment]
This is already being worked on in PR #25
