### ISSUE TITLE
Adding a cluster disk adds disks to the cluster

### ISSUE THREAD

**Issue by carpenike** [PowerShell/xFailOverCluster#4]
Hi there,

The Add-ClusterNode cmdlet is missing the -NoStorage option. The original node which creates the cluster contains that option and works as expected, but when the subsequent nodes are added all shared disks in the cluster are then added into the available storage.

Thanks,
Ryan

**Comment by JasonMorgan** [comment]
+1 This is really unfortunate.

**Comment by DdenBraver** [comment]
@TravisEz13 @KarolKaczmarek This issue should be resolved with Pull request #8

**Comment by TravisEz13** [comment]
Closing per comments. Please re-open or open a new issue if this is still an issue
