### ISSUE TITLE
xClusterDisk: Failing unit test 

### ISSUE THREAD

**Issue by johlju** [PowerShell/xFailOverCluster#55]
xClusterDisk is failing test.

https://ci.appveyor.com/project/johlju/xfailovercluster/build/1.6.1.0#L295

**Comment by johlju** [comment]
@bgelens Question, I usually keep the bug tag and only remove the In progress tag. So history is kept. You think we should remove bug and enhancement tags?

**Comment by bgelens** [comment]
I noticed in xHyper-V that labels where automatically removed. Figured it was good practice.

**Comment by johlju** [comment]
I doesn't in xSQLServer, it only removes In progress sametimes. That bot seems to work differently in different resources. 😆  I usally remove "In progress" and "Assignees". But we can remove all here too. It is up to us I guess. :)
