### ISSUE TITLE
Wrong cmdlet used to get Cluster Address Value

### ISSUE THREAD

**Issue by matthitchcock** [PowerShell/xFailOverCluster#6]
Line 38 is currently:
$address = Get-ClusterGroup -Cluster $Name -Name "Cluster IP Address" | Get-ClusterParameter "Address"

Should be:
$address = Get-ClusterResource -Cluster $Name -Name "Cluster IP Address" | Get-ClusterParameter -Name "Address"

Doesn't seem to work when using the Cluster Name as $Name, but does when using a Cluster Node Name as $Name.

This was tested when creating a 2 node cluster with Azure VMs.

**Comment by johlju** [comment]
It should be changed from
`$address = Get-ClusterGroup -Cluster $Name -Name "Cluster IP Address" | Get-ClusterParameter "Address"`
To: 
`$address = Get-ClusterGroup -Cluster $Name | Get-ClusterResource -Name "Cluster IP Address" | Get-ClusterParameter "Address"`

**Comment by DdenBraver** [comment]
@matthitchcock The fix was indeed as @johlju proposed, combined with returning the hashtable in the end.

**Comment by TravisEz13** [comment]
@DdenBraver what PR fixed this issue?

**Comment by DdenBraver** [comment]
@TravisEz13 PR #14 will fix this issue.
