### ISSUE TITLE
xClusterNetwork: Logic to add or remove networks does not exist

### ISSUE THREAD

**Issue by johlju** [PowerShell/xFailOverCluster#92]
**Details of the scenario you tried and the problem that is occurring:**
This resource should be able to add or remove Networks. Currently it only supports changing the name, role and the metric for a already present cluster network. 

The schema should add at least an Ensure parameter to be able to add and remove cluster network.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by mnewswanger** [comment]
I'm looking into implementing this so that we can support multi-subnet clusters.

I assume the following is intended behavior:

* Ensure: true - create the network
* Ensure: false - remove the network
* Ensure: null - default to true behavior

**Comment by johlju** [comment]
Please see the schema here for [xClusterDisk](https://github.com/PowerShell/xFailOverCluster/blob/dev/DSCResources/MSFT_xClusterDisk/MSFT_xClusterDisk.schema.mof) on how to use the parameter `Ensure`. Parameter `Ensure` is used like that in resources in all resource modules, so we shall not change the behavior.

So it should be:
- `Ensure -eq 'Present'` (the default value) - create the network.
- `Ensure -eq 'Absent'` - remove the network.

It would be awesome if you could work on this. Should I label this as "in progress"?

**Comment by mnewswanger** [comment]
Makes sense to me.

Go ahead and mark it as in-progress.

**Comment by johlju** [comment]
Awesome! Looking forward to review this change. 😄

**Comment by mnewswanger** [comment]
I think this one largely needs clarification no documentation.  There aren't any PS commandlets to manipulate cluster networks as it updates when networks are added / removed from cluster nodes.

**Comment by johlju** [comment]
@mnewswanger Ah, adding (creating) or removing (remove) network was bad terms to use. Maybe enable and disable networks would have been better? My point with the issue was that we do not support changing these values.

![image](https://user-images.githubusercontent.com/7189721/31574783-acf63ba6-b0d6-11e7-909e-66e43ba5167b.png)

More detailed explaination on how to [Modify Network Settings for a Failover Cluster](https://technet.microsoft.com/en-us/library/cc725775(v=ws.11).aspx).

And a forum discussion for [Adding additional network adapters to a cluster](https://social.technet.microsoft.com/Forums/windowsserver/en-US/311f7763-9f72-4dfe-bb35-3fd1a1dc567c/adding-additional-network-adapters-to-a-cluster?forum=winserverClustering).

**Comment by johlju** [comment]
@mnewswanger Sorry, my bad. We do support that! Didn't realize that the parameter Role did just that. Ignore my last comment.
